spring:
    application:
        name: "Spring Prometheus"
    jpa:
        open-in-view: false
server:
    port: 9881
management:
    endpoints:
        web:
            exposure:
                include: "*"
