version: '3.9'
services:
    prometheus:
        container_name: spring-prometheus
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - type: bind
              source: ./prometheus.yml
              target: /etc/prometheus/prometheus.yml

volumes:
    prometheus_volume: